// In-memory store for pending desktop OAuth tokens.
// device_id is generated by the Tauri client; token is a short-lived JWT.
// Works for single-process deployments (self-hosted, tauri dev).
// For multi-instance Vercel deployments, swap the Map for a DB table.

interface PendingEntry {
  token: string;
  expiresAt: number;
}

const store = new Map<string, PendingEntry>();

export function setPendingClientToken(deviceId: string, token: string): void {
  // Evict expired entries on every write to avoid unbounded growth.
  const now = Date.now();
  for (const [key, val] of store.entries()) {
    if (val.expiresAt < now) store.delete(key);
  }
  store.set(deviceId, { token, expiresAt: now + 5 * 60 * 1000 });
}

// Returns the token and removes it (one-time use). Returns null if missing/expired.
export function consumeClientToken(deviceId: string): string | null {
  const entry = store.get(deviceId);
  if (!entry || entry.expiresAt < Date.now()) {
    store.delete(deviceId);
    return null;
  }
  store.delete(deviceId);
  return entry.token;
}
