// Re-export all tables from the PostgreSQL schema.
// All existing imports like `import { users } from '@/db/schema'` continue to work.
export {
  workspaces,
  workspaceItems,
  standalonePages,
  databases,
  pages,
  users,
  accounts,
  sessions,
  verification,
  workspaceMembers,
  workspaceInvites,
  agentTokens,
  clientAuthTokens,
  userSessions,
  uploadedAssets,
  sharedPages,
  oauthClients,
  oauthAuthCodes,
  oauthAccessTokens,
  jwks,
  agentActivity,
  subscriptions,
  // Finance module
  financeAccounts,
  financeCards,
  financeCategories,
  financeTransactions,
  financeBudgets,
  financeGoals,
  financeSubscriptions,
  financeDebts,
  financeInvestments,
  financeInvestmentTransactions,
  financeRecurringRules,
} from './pg-schema';
