// Curated emoji dataset for the ":" inline emoji picker (EmojiExtension).
// name = canonical short-name typed after ":" (gemoji-style); keywords = extra search aliases.
export type EmojiEntry = { emoji: string; name: string; keywords: string[] };

export const EMOJI_LIST: EmojiEntry[] = [
  // Smileys & emotion
  { emoji: '😀', name: 'grinning', keywords: ['smile', 'happy'] },
  { emoji: '😃', name: 'smiley', keywords: ['happy', 'joy'] },
  { emoji: '😄', name: 'smile', keywords: ['happy', 'joy', 'laugh'] },
  { emoji: '😁', name: 'grin', keywords: ['happy'] },
  { emoji: '😆', name: 'laughing', keywords: ['haha', 'lol'] },
  { emoji: '😅', name: 'sweat_smile', keywords: ['phew', 'relief'] },
  { emoji: '🤣', name: 'rofl', keywords: ['rolling', 'laugh', 'lol'] },
  { emoji: '😂', name: 'joy', keywords: ['laugh', 'cry', 'lol'] },
  { emoji: '🙂', name: 'slightly_smiling_face', keywords: ['smile'] },
  { emoji: '🙃', name: 'upside_down_face', keywords: ['silly'] },
  { emoji: '😉', name: 'wink', keywords: [] },
  { emoji: '😊', name: 'blush', keywords: ['happy', 'shy'] },
  { emoji: '😇', name: 'innocent', keywords: ['angel', 'halo'] },
  { emoji: '🥰', name: 'smiling_face_with_hearts', keywords: ['love', 'crush'] },
  { emoji: '😍', name: 'heart_eyes', keywords: ['love', 'crush'] },
  { emoji: '🤩', name: 'star_struck', keywords: ['starstruck', 'wow'] },
  { emoji: '😘', name: 'kissing_heart', keywords: ['kiss', 'love'] },
  { emoji: '😗', name: 'kissing', keywords: [] },
  { emoji: '😋', name: 'yum', keywords: ['tasty', 'delicious'] },
  { emoji: '😛', name: 'stuck_out_tongue', keywords: ['tongue'] },
  { emoji: '😜', name: 'stuck_out_tongue_winking_eye', keywords: ['tongue', 'silly'] },
  { emoji: '🤪', name: 'zany_face', keywords: ['crazy', 'silly'] },
  { emoji: '😝', name: 'stuck_out_tongue_closed_eyes', keywords: ['tongue'] },
  { emoji: '🤑', name: 'money_mouth_face', keywords: ['money', 'rich'] },
  { emoji: '🤗', name: 'hugs', keywords: ['hug'] },
  { emoji: '🤭', name: 'hand_over_mouth', keywords: ['oops', 'giggle'] },
  { emoji: '🤫', name: 'shushing_face', keywords: ['quiet', 'shh', 'secret'] },
  { emoji: '🤔', name: 'thinking', keywords: ['hmm'] },
  { emoji: '🤐', name: 'zipper_mouth_face', keywords: ['quiet', 'secret'] },
  { emoji: '🤨', name: 'raised_eyebrow', keywords: ['suspicious', 'skeptical'] },
  { emoji: '😐', name: 'neutral_face', keywords: [] },
  { emoji: '😑', name: 'expressionless', keywords: [] },
  { emoji: '😶', name: 'no_mouth', keywords: ['silent'] },
  { emoji: '😏', name: 'smirk', keywords: [] },
  { emoji: '😒', name: 'unamused', keywords: ['annoyed'] },
  { emoji: '🙄', name: 'roll_eyes', keywords: ['eyeroll', 'whatever'] },
  { emoji: '😬', name: 'grimacing', keywords: ['awkward'] },
  { emoji: '🤥', name: 'lying_face', keywords: ['pinocchio', 'lie'] },
  { emoji: '😌', name: 'relieved', keywords: ['calm'] },
  { emoji: '😔', name: 'pensive', keywords: ['sad'] },
  { emoji: '😪', name: 'sleepy', keywords: ['tired'] },
  { emoji: '🤤', name: 'drooling_face', keywords: [] },
  { emoji: '😴', name: 'sleeping', keywords: ['zzz', 'sleep', 'tired'] },
  { emoji: '😷', name: 'mask', keywords: ['sick', 'ill'] },
  { emoji: '🤒', name: 'face_with_thermometer', keywords: ['sick', 'fever'] },
  { emoji: '🤕', name: 'face_with_head_bandage', keywords: ['hurt', 'injured'] },
  { emoji: '🤢', name: 'nauseated_face', keywords: ['sick', 'gross'] },
  { emoji: '🤮', name: 'vomiting_face', keywords: ['sick'] },
  { emoji: '🤧', name: 'sneezing_face', keywords: ['sick', 'cold'] },
  { emoji: '🥵', name: 'hot_face', keywords: ['heat'] },
  { emoji: '🥶', name: 'cold_face', keywords: ['freezing'] },
  { emoji: '🥴', name: 'woozy_face', keywords: ['dizzy'] },
  { emoji: '😵', name: 'dizzy_face', keywords: [] },
  { emoji: '🤯', name: 'exploding_head', keywords: ['mindblown', 'shocked'] },
  { emoji: '🤠', name: 'cowboy_hat_face', keywords: [] },
  { emoji: '🥳', name: 'partying_face', keywords: ['party', 'celebrate'] },
  { emoji: '🥸', name: 'disguised_face', keywords: ['disguise'] },
  { emoji: '😎', name: 'sunglasses', keywords: ['cool'] },
  { emoji: '🤓', name: 'nerd_face', keywords: ['geek', 'nerd'] },
  { emoji: '🧐', name: 'monocle_face', keywords: ['curious'] },
  { emoji: '😕', name: 'confused', keywords: [] },
  { emoji: '😟', name: 'worried', keywords: [] },
  { emoji: '🙁', name: 'slightly_frowning_face', keywords: ['sad'] },
  { emoji: '😮', name: 'open_mouth', keywords: ['surprised', 'wow'] },
  { emoji: '😯', name: 'hushed', keywords: ['surprised'] },
  { emoji: '😲', name: 'astonished', keywords: ['shocked', 'wow'] },
  { emoji: '😳', name: 'flushed', keywords: ['blush', 'embarrassed'] },
  { emoji: '🥺', name: 'pleading_face', keywords: ['puppy_eyes', 'please'] },
  { emoji: '😦', name: 'frowning', keywords: [] },
  { emoji: '😧', name: 'anguished', keywords: [] },
  { emoji: '😨', name: 'fearful', keywords: ['scared'] },
  { emoji: '😰', name: 'cold_sweat', keywords: ['nervous', 'anxious'] },
  { emoji: '😥', name: 'disappointed_relieved', keywords: ['sad'] },
  { emoji: '😢', name: 'cry', keywords: ['sad', 'tear'] },
  { emoji: '😭', name: 'sob', keywords: ['crying', 'sad'] },
  { emoji: '😱', name: 'scream', keywords: ['shocked', 'scared'] },
  { emoji: '😖', name: 'confounded', keywords: [] },
  { emoji: '😣', name: 'persevere', keywords: [] },
  { emoji: '😞', name: 'disappointed', keywords: ['sad'] },
  { emoji: '😓', name: 'sweat', keywords: [] },
  { emoji: '😩', name: 'weary', keywords: ['tired'] },
  { emoji: '😫', name: 'tired_face', keywords: [] },
  { emoji: '🥱', name: 'yawning_face', keywords: ['tired', 'sleepy'] },
  { emoji: '😤', name: 'triumph', keywords: ['proud'] },
  { emoji: '😡', name: 'rage', keywords: ['angry', 'mad'] },
  { emoji: '😠', name: 'angry', keywords: ['mad'] },
  { emoji: '🤬', name: 'cursing_face', keywords: ['swear', 'angry'] },
  { emoji: '😈', name: 'smiling_imp', keywords: ['devil'] },
  { emoji: '👿', name: 'imp', keywords: ['devil', 'angry'] },
  { emoji: '💀', name: 'skull', keywords: ['dead', 'death'] },
  { emoji: '👻', name: 'ghost', keywords: ['spooky'] },
  { emoji: '👽', name: 'alien', keywords: ['ufo'] },
  { emoji: '🤖', name: 'robot', keywords: ['bot', 'ai'] },
  { emoji: '💩', name: 'poop', keywords: ['shit', 'crap'] },
  // Gestures & body
  { emoji: '👋', name: 'wave', keywords: ['hello', 'bye', 'hand'] },
  { emoji: '🤚', name: 'raised_back_of_hand', keywords: [] },
  { emoji: '✋', name: 'hand', keywords: ['stop', 'high_five'] },
  { emoji: '👌', name: 'ok_hand', keywords: ['ok', 'perfect'] },
  { emoji: '🤌', name: 'pinched_fingers', keywords: ['italian'] },
  { emoji: '🤏', name: 'pinching_hand', keywords: ['small', 'little'] },
  { emoji: '✌️', name: 'v', keywords: ['peace', 'victory'] },
  { emoji: '🤞', name: 'crossed_fingers', keywords: ['luck', 'hope'] },
  { emoji: '🤟', name: 'love_you_gesture', keywords: [] },
  { emoji: '🤘', name: 'metal', keywords: ['rock'] },
  { emoji: '👈', name: 'point_left', keywords: [] },
  { emoji: '👉', name: 'point_right', keywords: [] },
  { emoji: '👆', name: 'point_up_2', keywords: [] },
  { emoji: '👇', name: 'point_down', keywords: [] },
  { emoji: '☝️', name: 'point_up', keywords: [] },
  { emoji: '👍', name: 'thumbsup', keywords: ['like', 'approve', 'yes'] },
  { emoji: '👎', name: 'thumbsdown', keywords: ['dislike', 'no'] },
  { emoji: '✊', name: 'fist', keywords: ['power'] },
  { emoji: '👊', name: 'fist_oncoming', keywords: ['punch', 'bump'] },
  { emoji: '🤛', name: 'fist_left', keywords: [] },
  { emoji: '🤜', name: 'fist_right', keywords: [] },
  { emoji: '👏', name: 'clap', keywords: ['applause', 'bravo'] },
  { emoji: '🙌', name: 'raised_hands', keywords: ['celebrate', 'praise'] },
  { emoji: '👐', name: 'open_hands', keywords: [] },
  { emoji: '🤲', name: 'palms_up_together', keywords: ['pray'] },
  { emoji: '🙏', name: 'pray', keywords: ['thanks', 'please'] },
  { emoji: '✍️', name: 'writing_hand', keywords: ['write'] },
  { emoji: '💪', name: 'muscle', keywords: ['strong', 'flex', 'gym'] },
  { emoji: '🦾', name: 'mechanical_arm', keywords: [] },
  { emoji: '🧠', name: 'brain', keywords: ['smart', 'mind'] },
  { emoji: '👀', name: 'eyes', keywords: ['look', 'see'] },
  { emoji: '👁️', name: 'eye', keywords: [] },
  { emoji: '👅', name: 'tongue', keywords: [] },
  { emoji: '👄', name: 'lips', keywords: ['mouth', 'kiss'] },
  // Hearts & symbols
  { emoji: '❤️', name: 'heart', keywords: ['love', 'red'] },
  { emoji: '🧡', name: 'orange_heart', keywords: ['love'] },
  { emoji: '💛', name: 'yellow_heart', keywords: ['love'] },
  { emoji: '💚', name: 'green_heart', keywords: ['love'] },
  { emoji: '💙', name: 'blue_heart', keywords: ['love'] },
  { emoji: '💜', name: 'purple_heart', keywords: ['love'] },
  { emoji: '🖤', name: 'black_heart', keywords: ['love'] },
  { emoji: '🤍', name: 'white_heart', keywords: ['love'] },
  { emoji: '🤎', name: 'brown_heart', keywords: ['love'] },
  { emoji: '💔', name: 'broken_heart', keywords: ['sad', 'breakup'] },
  { emoji: '❣️', name: 'heart_exclamation', keywords: [] },
  { emoji: '💕', name: 'two_hearts', keywords: ['love'] },
  { emoji: '💞', name: 'revolving_hearts', keywords: ['love'] },
  { emoji: '💓', name: 'heartbeat', keywords: ['love', 'pulse'] },
  { emoji: '💗', name: 'heartpulse', keywords: ['love'] },
  { emoji: '💖', name: 'sparkling_heart', keywords: ['love'] },
  { emoji: '💘', name: 'cupid', keywords: ['love', 'arrow'] },
  { emoji: '💝', name: 'gift_heart', keywords: ['love', 'present'] },
  { emoji: '💯', name: 'hundred', keywords: ['100', 'perfect', 'score'] },
  { emoji: '💢', name: 'anger', keywords: ['mad'] },
  { emoji: '💥', name: 'boom', keywords: ['explosion', 'bang'] },
  { emoji: '💫', name: 'dizzy', keywords: ['star'] },
  { emoji: '💦', name: 'sweat_drops', keywords: ['water'] },
  { emoji: '💨', name: 'dash', keywords: ['wind', 'fast', 'run'] },
  { emoji: '🕳️', name: 'hole', keywords: [] },
  { emoji: '💬', name: 'speech_balloon', keywords: ['chat', 'talk', 'comment'] },
  { emoji: '💭', name: 'thought_balloon', keywords: ['think'] },
  { emoji: '💤', name: 'zzz', keywords: ['sleep'] },
  { emoji: '✅', name: 'white_check_mark', keywords: ['check', 'done', 'yes'] },
  { emoji: '✔️', name: 'heavy_check_mark', keywords: ['check', 'done'] },
  { emoji: '☑️', name: 'ballot_box_with_check', keywords: ['check', 'done'] },
  { emoji: '❌', name: 'x', keywords: ['cross', 'no', 'wrong'] },
  { emoji: '❎', name: 'negative_squared_cross_mark', keywords: ['no'] },
  { emoji: '➕', name: 'heavy_plus_sign', keywords: ['add', 'plus'] },
  { emoji: '➖', name: 'heavy_minus_sign', keywords: ['minus', 'subtract'] },
  { emoji: '❓', name: 'question', keywords: ['help', 'ask'] },
  { emoji: '❗', name: 'exclamation', keywords: ['warning', 'important'] },
  { emoji: '⚠️', name: 'warning', keywords: ['caution', 'alert'] },
  { emoji: '🚫', name: 'no_entry_sign', keywords: ['forbidden', 'stop'] },
  { emoji: '🔒', name: 'lock', keywords: ['secure', 'private'] },
  { emoji: '🔓', name: 'unlock', keywords: ['open'] },
  { emoji: '🔑', name: 'key', keywords: ['password'] },
  { emoji: '🔔', name: 'bell', keywords: ['notification', 'alert'] },
  { emoji: '🔕', name: 'no_bell', keywords: ['mute', 'silent'] },
  { emoji: '⭐', name: 'star', keywords: ['favorite'] },
  { emoji: '🌟', name: 'star2', keywords: ['sparkle'] },
  { emoji: '✨', name: 'sparkles', keywords: ['shiny', 'new'] },
  { emoji: '⚡', name: 'zap', keywords: ['lightning', 'fast', 'power'] },
  { emoji: '🔥', name: 'fire', keywords: ['hot', 'lit', 'flame'] },
  { emoji: '🎯', name: 'dart', keywords: ['target', 'goal', 'focus'] },
  { emoji: '🏆', name: 'trophy', keywords: ['win', 'award', 'winner'] },
  { emoji: '🥇', name: 'first_place_medal', keywords: ['gold', 'winner'] },
  { emoji: '🎉', name: 'tada', keywords: ['celebrate', 'party', 'confetti'] },
  { emoji: '🎊', name: 'confetti_ball', keywords: ['party', 'celebrate'] },
  { emoji: '🎁', name: 'gift', keywords: ['present'] },
  { emoji: '🏁', name: 'checkered_flag', keywords: ['finish', 'done'] },
  { emoji: '🚀', name: 'rocket', keywords: ['launch', 'fast', 'ship'] },
  { emoji: '🛸', name: 'flying_saucer', keywords: ['ufo'] },
  { emoji: '💡', name: 'bulb', keywords: ['idea', 'light'] },
  { emoji: '🔦', name: 'flashlight', keywords: ['light'] },
  { emoji: '📌', name: 'pushpin', keywords: ['pin'] },
  { emoji: '📍', name: 'round_pushpin', keywords: ['location', 'pin'] },
  { emoji: '🔖', name: 'bookmark', keywords: ['tag', 'save'] },
  { emoji: '🏷️', name: 'label', keywords: ['tag'] },
  { emoji: '📎', name: 'paperclip', keywords: ['attachment'] },
  { emoji: '🔗', name: 'link', keywords: ['url', 'chain'] },
  { emoji: '🧷', name: 'safety_pin', keywords: [] },
  { emoji: '⏰', name: 'alarm_clock', keywords: ['time'] },
  { emoji: '⏱️', name: 'stopwatch', keywords: ['time'] },
  { emoji: '⏳', name: 'hourglass_flowing_sand', keywords: ['time', 'wait'] },
  { emoji: '⌛', name: 'hourglass', keywords: ['time', 'wait'] },
  { emoji: '🕐', name: 'clock1', keywords: ['time'] },
  { emoji: '📅', name: 'calendar', keywords: ['date', 'schedule'] },
  { emoji: '🗓️', name: 'spiral_calendar', keywords: ['date', 'schedule'] },
  { emoji: '📆', name: 'tear_off_calendar', keywords: ['date'] },
  // Objects / work
  { emoji: '📝', name: 'memo', keywords: ['note', 'write', 'pencil'] },
  { emoji: '✏️', name: 'pencil2', keywords: ['write', 'edit'] },
  { emoji: '🖊️', name: 'pen', keywords: ['write'] },
  { emoji: '📄', name: 'page_facing_up', keywords: ['document', 'file'] },
  { emoji: '📃', name: 'page_with_curl', keywords: ['document'] },
  { emoji: '📑', name: 'bookmark_tabs', keywords: ['tabs'] },
  { emoji: '📊', name: 'bar_chart', keywords: ['chart', 'graph', 'stats'] },
  { emoji: '📈', name: 'chart_with_upwards_trend', keywords: ['growth', 'stats', 'increase'] },
  { emoji: '📉', name: 'chart_with_downwards_trend', keywords: ['decline', 'decrease'] },
  { emoji: '📋', name: 'clipboard', keywords: ['tasks', 'list'] },
  { emoji: '📁', name: 'file_folder', keywords: ['folder'] },
  { emoji: '📂', name: 'open_file_folder', keywords: ['folder'] },
  { emoji: '🗂️', name: 'card_index_dividers', keywords: ['organize'] },
  { emoji: '📚', name: 'books', keywords: ['read', 'library'] },
  { emoji: '📖', name: 'open_book', keywords: ['read'] },
  { emoji: '🔍', name: 'mag', keywords: ['search', 'find', 'zoom'] },
  { emoji: '🔎', name: 'mag_right', keywords: ['search', 'find'] },
  { emoji: '⚙️', name: 'gear', keywords: ['settings', 'config'] },
  { emoji: '🛠️', name: 'hammer_and_wrench', keywords: ['tools', 'fix'] },
  { emoji: '🔧', name: 'wrench', keywords: ['fix', 'tool'] },
  { emoji: '🔨', name: 'hammer', keywords: ['build', 'fix'] },
  { emoji: '🧰', name: 'toolbox', keywords: ['tools'] },
  { emoji: '🔩', name: 'nut_and_bolt', keywords: [] },
  { emoji: '💻', name: 'computer', keywords: ['laptop', 'code'] },
  { emoji: '🖥️', name: 'desktop_computer', keywords: ['pc'] },
  { emoji: '⌨️', name: 'keyboard', keywords: ['type'] },
  { emoji: '🖱️', name: 'computer_mouse', keywords: [] },
  { emoji: '💾', name: 'floppy_disk', keywords: ['save'] },
  { emoji: '💿', name: 'cd', keywords: ['disk'] },
  { emoji: '📱', name: 'iphone', keywords: ['phone', 'mobile'] },
  { emoji: '☎️', name: 'phone', keywords: ['call'] },
  { emoji: '📞', name: 'telephone_receiver', keywords: ['call'] },
  { emoji: '📧', name: 'e-mail', keywords: ['mail', 'email'] },
  { emoji: '✉️', name: 'envelope', keywords: ['mail', 'email'] },
  { emoji: '📨', name: 'incoming_envelope', keywords: ['mail'] },
  { emoji: '📤', name: 'outbox_tray', keywords: ['send'] },
  { emoji: '📥', name: 'inbox_tray', keywords: ['receive', 'inbox'] },
  { emoji: '🗃️', name: 'card_file_box', keywords: ['database', 'archive'] },
  { emoji: '🗄️', name: 'file_cabinet', keywords: ['archive'] },
  { emoji: '🗑️', name: 'wastebasket', keywords: ['trash', 'delete', 'bin'] },
  { emoji: '🔐', name: 'closed_lock_with_key', keywords: ['secure', 'password'] },
  { emoji: '🧩', name: 'jigsaw', keywords: ['puzzle', 'piece'] },
  { emoji: '🪄', name: 'magic_wand', keywords: ['magic'] },
  { emoji: '🧪', name: 'test_tube', keywords: ['test', 'lab', 'experiment'] },
  { emoji: '🔬', name: 'microscope', keywords: ['science'] },
  { emoji: '🔭', name: 'telescope', keywords: ['space'] },
  { emoji: '📡', name: 'satellite', keywords: ['signal'] },
  { emoji: '💰', name: 'moneybag', keywords: ['money', 'cash'] },
  { emoji: '💵', name: 'dollar', keywords: ['money', 'cash'] },
  { emoji: '💳', name: 'credit_card', keywords: ['money', 'payment'] },
  { emoji: '💎', name: 'gem', keywords: ['diamond', 'jewel'] },
  { emoji: '⚖️', name: 'balance_scale', keywords: ['law', 'justice'] },
  { emoji: '🧲', name: 'magnet', keywords: [] },
  // People / status
  { emoji: '🧑‍💻', name: 'technologist', keywords: ['developer', 'coder', 'programmer'] },
  { emoji: '👨‍💻', name: 'man_technologist', keywords: ['developer', 'coder'] },
  { emoji: '👩‍💻', name: 'woman_technologist', keywords: ['developer', 'coder'] },
  { emoji: '🧑‍🎨', name: 'artist', keywords: ['design', 'paint'] },
  { emoji: '🧑‍🚀', name: 'astronaut', keywords: ['space'] },
  { emoji: '🧑‍🏫', name: 'teacher', keywords: [] },
  { emoji: '🕵️', name: 'detective', keywords: ['spy', 'investigate'] },
  { emoji: '🧙', name: 'mage', keywords: ['wizard'] },
  { emoji: '🦸', name: 'superhero', keywords: ['hero'] },
  // Animals & nature
  { emoji: '🐶', name: 'dog', keywords: [] },
  { emoji: '🐱', name: 'cat', keywords: [] },
  { emoji: '🐭', name: 'mouse', keywords: [] },
  { emoji: '🐹', name: 'hamster', keywords: [] },
  { emoji: '🐰', name: 'rabbit', keywords: ['bunny'] },
  { emoji: '🦊', name: 'fox_face', keywords: [] },
  { emoji: '🐻', name: 'bear', keywords: [] },
  { emoji: '🐼', name: 'panda_face', keywords: [] },
  { emoji: '🐨', name: 'koala', keywords: [] },
  { emoji: '🐯', name: 'tiger', keywords: [] },
  { emoji: '🦁', name: 'lion', keywords: [] },
  { emoji: '🐮', name: 'cow', keywords: [] },
  { emoji: '🐷', name: 'pig', keywords: [] },
  { emoji: '🐸', name: 'frog', keywords: [] },
  { emoji: '🐵', name: 'monkey_face', keywords: [] },
  { emoji: '🐔', name: 'chicken', keywords: [] },
  { emoji: '🐧', name: 'penguin', keywords: [] },
  { emoji: '🐦', name: 'bird', keywords: [] },
  { emoji: '🦅', name: 'eagle', keywords: [] },
  { emoji: '🦉', name: 'owl', keywords: [] },
  { emoji: '🐴', name: 'horse', keywords: [] },
  { emoji: '🦄', name: 'unicorn', keywords: [] },
  { emoji: '🐝', name: 'bee', keywords: ['bug'] },
  { emoji: '🐛', name: 'bug', keywords: ['insect'] },
  { emoji: '🦋', name: 'butterfly', keywords: [] },
  { emoji: '🐢', name: 'turtle', keywords: ['slow'] },
  { emoji: '🐍', name: 'snake', keywords: [] },
  { emoji: '🐳', name: 'whale', keywords: [] },
  { emoji: '🐬', name: 'dolphin', keywords: [] },
  { emoji: '🐟', name: 'fish', keywords: [] },
  { emoji: '🐙', name: 'octopus', keywords: [] },
  { emoji: '🦀', name: 'crab', keywords: [] },
  { emoji: '🐾', name: 'paw_prints', keywords: ['pet', 'animal'] },
  { emoji: '🌵', name: 'cactus', keywords: [] },
  { emoji: '🌲', name: 'evergreen_tree', keywords: ['tree'] },
  { emoji: '🌳', name: 'deciduous_tree', keywords: ['tree'] },
  { emoji: '🌴', name: 'palm_tree', keywords: [] },
  { emoji: '🌱', name: 'seedling', keywords: ['plant', 'growth', 'new'] },
  { emoji: '🌿', name: 'herb', keywords: ['plant'] },
  { emoji: '☘️', name: 'shamrock', keywords: ['luck', 'clover'] },
  { emoji: '🍀', name: 'four_leaf_clover', keywords: ['luck'] },
  { emoji: '🌸', name: 'cherry_blossom', keywords: ['flower'] },
  { emoji: '🌹', name: 'rose', keywords: ['flower', 'love'] },
  { emoji: '🌻', name: 'sunflower', keywords: ['flower'] },
  { emoji: '🌼', name: 'blossom', keywords: ['flower'] },
  { emoji: '🌷', name: 'tulip', keywords: ['flower'] },
  { emoji: '🍁', name: 'maple_leaf', keywords: ['autumn', 'fall'] },
  { emoji: '🍂', name: 'fallen_leaf', keywords: ['autumn'] },
  { emoji: '🍃', name: 'leaves', keywords: ['wind', 'nature'] },
  { emoji: '☀️', name: 'sunny', keywords: ['sun', 'weather'] },
  { emoji: '🌤️', name: 'sun_behind_small_cloud', keywords: ['weather'] },
  { emoji: '⛅', name: 'partly_sunny', keywords: ['weather', 'cloud'] },
  { emoji: '☁️', name: 'cloud', keywords: ['weather'] },
  { emoji: '🌧️', name: 'cloud_with_rain', keywords: ['weather', 'rain'] },
  { emoji: '⛈️', name: 'thunder_cloud_rain', keywords: ['storm'] },
  { emoji: '🌩️', name: 'cloud_with_lightning', keywords: ['storm'] },
  { emoji: '❄️', name: 'snowflake', keywords: ['snow', 'winter', 'cold'] },
  { emoji: '☃️', name: 'snowman_with_snow', keywords: ['winter'] },
  { emoji: '🌈', name: 'rainbow', keywords: [] },
  { emoji: '🌙', name: 'crescent_moon', keywords: ['night'] },
  { emoji: '🌛', name: 'first_quarter_moon_with_face', keywords: [] },
  { emoji: '⭐', name: 'star_alt', keywords: [] },
  { emoji: '🌍', name: 'earth_africa', keywords: ['world', 'globe'] },
  { emoji: '🌎', name: 'earth_americas', keywords: ['world', 'globe'] },
  { emoji: '🌐', name: 'globe_with_meridians', keywords: ['world', 'internet', 'web'] },
  // Food & drink
  { emoji: '☕', name: 'coffee', keywords: ['tea', 'drink'] },
  { emoji: '🍵', name: 'tea', keywords: ['drink'] },
  { emoji: '🍺', name: 'beer', keywords: ['drink'] },
  { emoji: '🍻', name: 'beers', keywords: ['cheers', 'drink'] },
  { emoji: '🍷', name: 'wine_glass', keywords: ['drink'] },
  { emoji: '🍾', name: 'champagne', keywords: ['celebrate', 'drink'] },
  { emoji: '🥂', name: 'clinking_glasses', keywords: ['cheers', 'celebrate'] },
  { emoji: '🍕', name: 'pizza', keywords: ['food'] },
  { emoji: '🍔', name: 'hamburger', keywords: ['food', 'burger'] },
  { emoji: '🍟', name: 'fries', keywords: ['food'] },
  { emoji: '🌭', name: 'hotdog', keywords: ['food'] },
  { emoji: '🍿', name: 'popcorn', keywords: ['snack', 'movie'] },
  { emoji: '🥐', name: 'croissant', keywords: ['food', 'bread'] },
  { emoji: '🍞', name: 'bread', keywords: ['food'] },
  { emoji: '🧀', name: 'cheese', keywords: ['food'] },
  { emoji: '🥚', name: 'egg', keywords: ['food'] },
  { emoji: '🍳', name: 'fried_egg', keywords: ['food', 'breakfast'] },
  { emoji: '🥗', name: 'green_salad', keywords: ['food', 'healthy'] },
  { emoji: '🍜', name: 'ramen', keywords: ['food', 'noodles'] },
  { emoji: '🍣', name: 'sushi', keywords: ['food'] },
  { emoji: '🍰', name: 'cake', keywords: ['dessert', 'birthday'] },
  { emoji: '🎂', name: 'birthday', keywords: ['cake', 'party'] },
  { emoji: '🍩', name: 'doughnut', keywords: ['food', 'donut'] },
  { emoji: '🍪', name: 'cookie', keywords: ['food'] },
  { emoji: '🍫', name: 'chocolate_bar', keywords: ['food'] },
  { emoji: '🍎', name: 'apple', keywords: ['fruit'] },
  { emoji: '🍌', name: 'banana', keywords: ['fruit'] },
  { emoji: '🍇', name: 'grapes', keywords: ['fruit'] },
  { emoji: '🍓', name: 'strawberry', keywords: ['fruit'] },
  { emoji: '🥑', name: 'avocado', keywords: ['fruit'] },
  // Travel & places
  { emoji: '🏠', name: 'house', keywords: ['home'] },
  { emoji: '🏢', name: 'office', keywords: ['building', 'work'] },
  { emoji: '🏭', name: 'factory', keywords: [] },
  { emoji: '🏦', name: 'bank', keywords: ['money'] },
  { emoji: '🏥', name: 'hospital', keywords: ['health'] },
  { emoji: '🏫', name: 'school', keywords: ['education'] },
  { emoji: '⛰️', name: 'mountain', keywords: [] },
  { emoji: '🏔️', name: 'mountain_snow', keywords: [] },
  { emoji: '🏝️', name: 'desert_island', keywords: ['beach', 'vacation'] },
  { emoji: '🏖️', name: 'beach_umbrella', keywords: ['vacation', 'summer'] },
  { emoji: '🗺️', name: 'world_map', keywords: ['map', 'travel'] },
  { emoji: '🧭', name: 'compass', keywords: ['direction', 'navigate'] },
  { emoji: '✈️', name: 'airplane', keywords: ['travel', 'flight'] },
  { emoji: '🚗', name: 'car', keywords: ['drive'] },
  { emoji: '🚕', name: 'taxi', keywords: [] },
  { emoji: '🚲', name: 'bike', keywords: ['bicycle'] },
  { emoji: '🚆', name: 'train2', keywords: ['train'] },
  { emoji: '🚀', name: 'rocket_alt', keywords: [] },
  { emoji: '⚓', name: 'anchor', keywords: ['boat'] },
  { emoji: '🚦', name: 'vertical_traffic_light', keywords: [] },
  // Activities
  { emoji: '🎮', name: 'video_game', keywords: ['gaming', 'controller'] },
  { emoji: '🎲', name: 'game_die', keywords: ['dice'] },
  { emoji: '🎸', name: 'guitar', keywords: ['music'] },
  { emoji: '🎧', name: 'headphones', keywords: ['music', 'audio'] },
  { emoji: '🎵', name: 'musical_note', keywords: ['music'] },
  { emoji: '🎶', name: 'notes', keywords: ['music'] },
  { emoji: '🎤', name: 'microphone', keywords: ['sing', 'karaoke'] },
  { emoji: '🎬', name: 'clapper', keywords: ['movie', 'film'] },
  { emoji: '🎨', name: 'art', keywords: ['paint', 'design', 'palette'] },
  { emoji: '⚽', name: 'soccer', keywords: ['football'] },
  { emoji: '🏀', name: 'basketball', keywords: [] },
  { emoji: '🏈', name: 'football', keywords: ['american_football'] },
  { emoji: '⚾', name: 'baseball', keywords: [] },
  { emoji: '🎾', name: 'tennis', keywords: [] },
  { emoji: '🏓', name: 'ping_pong', keywords: ['table_tennis'] },
  { emoji: '🏋️', name: 'weight_lifting', keywords: ['gym', 'exercise'] },
  { emoji: '🧘', name: 'lotus_position', keywords: ['yoga', 'meditation', 'calm'] },
];
